media: 
 - name: images
   label: Media
   input: src/images
   output: images
   extensions: [ png, webp ]
content:
  - name: portfolio
    label: Portfolio Projects
    type: collection
    path: src/content/portfolio
    extension: yml
    view:
      fields: [ title, image, order ]
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: image
        label: Image
        type: image
        required: true
      - name: order
        label: Order
        type: number