media: 
  - name: images
    label: Images
    input: src/images
    output: images
    extensions: [ png, webp, jpg ]
content:
  - name: site-settings
    label: Site Settings
    path: src/config/site.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be used for any page with no description.
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?://)?(www.)?[a-zA-Z0-9.-]+.[a-zA-Z]{2,}(/[^s]*)?$
      - name: cover
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)
  - name: socials
    label: Social Settings
    path: src/config/socials.json
    type: file
    fields:
      - name: social_links
        label: Social Media Links
        list: true  # Use a list type to allow multiple entries
        fields:
          - name: platform
            label: Platform Name (e.g., Facebook, Twitter)
            type: string
            required: true
          - name: url
            label: URL
            type: string
            required: true
            pattern: ^https?://.*  # Ensure it's a valid URL
