collections:
  - name: pages
    label: Pages
    folder: src/content/pages
    create: true
    fields:
      - name: title
        label: Title
        type: text
      - name: body
        label: Content
        type: markdown

  - name: gallery
    label: Gallery
    folder: src/content/gallery
    create: true
    fields:
      - name: image
        label: Image
        type: image
      - name: alt
        label: Alt text
        type: text
        required: false

